### ISSUE TITLE
找不到类，是姿势不对吗？

### ISSUE THREAD

**Issue by lany192** [Leifzhang/AndroidAutoTrack#15]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/a/doubleclickplugin/DoubleTapCheck;

引用情况：
classpath 'com.kronos.doubleTap:double_tap_plugin:0.1.5'

apply plugin: 'doubleTap'

doubleTab {
    injectClassName = "com.a.doubleclickplugin.DoubleTapCheck"
    injectFunctionName = "isNotDoubleTap"
}

**Comment by Leifzhang** [comment]
com.a.doubleclickplugin.DoubleTapCheck 这个是你自己的类  做双击检查的

**Comment by Leifzhang** [comment]
https://github.com/Leifzhang/AndroidAutoTrack/blob/master/app/src/main/java/com/wallstreetcn/sample/DoubleTapCheck.kt  参考下这个类

**Comment by lany192** [comment]
明白了，没有认真看这个配置 injectClassName = "com.a.doubleclickplugin.DoubleTapCheck"
