### ISSUE TITLE
大佬，clone下来项目，没跑起来，build报错了

### ISSUE THREAD

**Issue by xuywei** [Leifzhang/AndroidAutoTrack#20]
> Task :app:dexBuilderDebug
AGPBI: {"kind":"error","text":"Type com.wallstreetcn.sample.adapter.OtherTestViewHolder$1 is defined multiple times: C:\\Users\\sxw\\Desktop\\AndroidAutoTrack\\app\\build\\intermediates\\transforms\\NewAutoTackTransform\\debug\\35\\com\\wallstreetcn\\sample\\adapter\\OtherTestViewHolder$1.class, C:\\Users\\sxw\\Desktop\\AndroidAutoTrack\\app\\build\\intermediates\\transforms\\NewAutoTackTransform\\debug\\35\\temp\\com\\wallstreetcn\\sample\\adapter\\OtherTestViewHolder$1.class","sources":[{"file":"C:\\Users\\sxw\\Desktop\\AndroidAutoTrack\\app\\build\\intermediates\\transforms\\NewAutoTackTransform\\debug\\35\\com\\wallstreetcn\\sample\\adapter\\OtherTestViewHolder$1.class"}],"tool":"D8"}
AGPBI: {"kind":"error","text":"Type com.wallstreetcn.sample.adapter.Test is defined multiple times: C:\\Users\\sxw\\Desktop\\AndroidAutoTrack\\app\\build\\intermediates\\transforms\\NewAutoTackTransform\\debug\\36\\com\\wallstreetcn\\sample\\adapter\\Test.class, C:\\Users\\sxw\\Desktop\\AndroidAutoTrack\\app\\build\\intermediates\\transforms\\NewAutoTackTransform\\debug\\36\\temp\\com\\wallstreetcn\\sample\\adapter\\Test.class","sources":[{"file":"C:\\Users\\sxw\\Desktop\\AndroidAutoTrack\\app\\build\\intermediates\\transforms\\NewAutoTackTransform\\debug\\36\\com\\wallstreetcn\\sample\\adapter\\Test.class"}],"tool":"D8"}
AGPBI: {"kind":"error","text":"Type com.wallstreetcn.sample.App is defined multiple times: C:\\Users\\sxw\\Desktop\\AndroidAutoTrack\\app\\build\\intermediates\\transforms\\NewAutoTackTransform\\debug\\36\\com\\wallstreetcn\\sample\\App.class, C:\\Users\\sxw\\Desktop\\AndroidAutoTrack\\app\\build\\intermediates\\transforms\\NewAutoTackTransform\\debug\\36\\temp\\com\\wallstreetcn\\sample\\App.class","sources":[{"file":"C:\\Users\\sxw\\Desktop\\AndroidAutoTrack\\app\\build\\intermediates\\transforms\\NewAutoTackTransform\\debug\\36\\com\\wallstreetcn\\sample\\App.class"}],"tool":"D8"}
AGPBI: {"kind":"error","text":"Type com.wallstreetcn.sample.utils.TestIOThreadExecutor$Companion$THREAD_POOL_SHARE$2 is defined multiple times: C:\\Users\\sxw\\Desktop\\AndroidAutoTrack\\app\\build\\intermediates\\transforms\\NewAutoTackTransform\\debug\\36\\com\\wallstreetcn\\sample\\utils\\TestIOThreadExecutor$Companion$THREAD_POOL_SHARE$2.class, C:\\Users\\sxw\\Desktop\\AndroidAutoTrack\\app\\build\\intermediates\\transforms\\NewAutoTackTransform\\debug\\36\\temp\\com\\wallstreetcn\\sample\\utils\\TestIOThreadExecutor$Companion$THREAD_POOL_SHARE$2.class","sources":[{"file":"C:\\Users\\sxw\\Desktop\\AndroidAutoTrack\\app\\build\\intermediates\\transforms\\NewAutoTackTransform\\debug\\36\\com\\wallstreetcn\\sample\\utils\\TestIOThreadExecutor$Companion$THREAD_POOL_SHARE$2.class"}],"tool":"D8"}

**Comment by xuywei** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexBuilderDebug'.
> There were multiple failures while executing work items
   > A failure occurred while executing com.android.build.gradle.internal.tasks.DexArchiveBuilderTaskDelegate$DexConversionWorkAction
      > Failed to process C:\Users\sxw\Desktop\AndroidAutoTrack\app\build\intermediates\transforms\NewAutoTackTransform\debug\35
   > A failure occurred while executing com.android.build.gradle.internal.tasks.DexArchiveBuilderTaskDelegate$DexConversionWorkAction
      > Failed to process C:\Users\sxw\Desktop\AndroidAutoTrack\app\build\intermediates\transforms\NewAutoTackTransform\debug\36
   > A failure occurred while executing com.android.build.gradle.internal.tasks.DexArchiveBuilderTaskDelegate$DexConversionWorkAction
      > Failed to process C:\Users\sxw\Desktop\AndroidAutoTrack\app\build\intermediates\transforms\NewAutoTackTransform\debug\36
   > A failure occurred while executing com.android.build.gradle.internal.tasks.DexArchiveBuilderTaskDelegate$DexConversionWorkAction
      > Failed to process C:\Users\sxw\Desktop\AndroidAutoTrack\app\build\intermediates\transforms\NewAutoTackTransform\debug\36

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

**Comment by Leifzhang** [comment]
加我qq聊吧  感觉怪怪的 454327998

**Comment by Leifzhang** [comment]
已经修复了  windows 文件流没关闭
