### ISSUE TITLE
处理连击哪里，使用lambda表达式setClickListener的点击事件无效啊，具体原因没看

### ISSUE THREAD

**Issue by gaozongy** [Leifzhang/AndroidAutoTrack#24]

**Comment by Leifzhang** [comment]
双击的lambda我还没处理，原因是因为desugar被移动到R8流程内了导致的，我在autoTrack那边处理了lambda，但是双击的由于插入的是一个类，所以lambda相对来说不好处理。
可以参考下https://github.com/Leifzhang/AndroidAutoTrack/blob/master/Plugin/AutoTrackPlugin/src/main/java/com/wallstreetcn/autotrack/helper/LambdaNodeHelper.kt   这里处理好了lambda ，所有的插入操作应该都在AsmHelper 中

**Comment by gaozongy** [comment]
多谢大佬回复，学习到了

**Comment by Leifzhang** [comment]
双击的如果是个静态方法应该好是比较简单的
