### ISSUE TITLE
下载代码编译后报错

### ISSUE THREAD

**Issue by wincentytg** [Leifzhang/AndroidAutoTrack#29]
\AndroidAutoTrack-master\Plugin\local.properties (系统找不到指定的文件。)

**Comment by Leifzhang** [comment]
自己加一个local.properties就好了 和外面的一样就行

**Comment by wincentytg** [comment]
大神 学习这个插件开发 有没有入门的文章推荐啊？看代码看的有点蒙

**Comment by wincentytg** [comment]
弄不清楚插件代码的调用先后逻辑 是在哪里触发的，想找个入门级别的文章看看，谢谢。

**Comment by Leifzhang** [comment]
建议先从安卓的编译流程开始了解下   gradle task  啥的 相对来说会比较入门  
https://blog.csdn.net/a296777513/article/details/90665134 可以看看这个大佬的

**Comment by wincentytg** [comment]
谢谢

**Comment by wincentytg** [comment]
代码里这个annotation class Test    Test注解的作用是啥？

**Comment by Leifzhang** [comment]
这个是我的玩具啊  因为涉及参数传递 所以我需要一个注解标识下  那个数据是要传递的
