### ISSUE TITLE
编译扫描阶段，仅dir添加到了线程池执行，为何jar没有依据此执行线程池执行？

### ISSUE THREAD

**Issue by yanchunlan** [Leifzhang/AndroidAutoTrack#30]

**Comment by Leifzhang** [comment]
大佬 这个问题问的很好呀 
其实是这样的 因为jar 文件zip 解完之后需要重新还原 之后在进行覆盖 如果这部分替换成多线程操作之后 首先要写个countdownlaunch  计算是否所有task都玩成了 然后根据temp文件重新合成jar  会让这部分的复杂度直线上升 而且有一说一  多线程之后最大的问题还是在于文件io

**Comment by Leifzhang** [comment]
周末划水没注意看邮箱 回复的慢了  大佬

**Comment by yanchunlan** [comment]
看了代码，针对jar目前是没做优化，这里可以在继续优化优化

**Comment by Leifzhang** [comment]
这部分可能漏掉了 单一的jar转化是可以直接放在线程内执行的  如果是要对jar内class是略微复杂了点

**Comment by Leifzhang** [comment]
给大佬补充好了 我略微测试了下 提速相对来说还是比较客观的
