### ISSUE TITLE
写一个自定义的注解，实现有的方法不需要防止快速双击

### ISSUE THREAD

**Issue by iblue007** [Leifzhang/AndroidAutoTrack#35]
我写了一个自定义注解，但是在transfrom方法里面找不到我添加的注解，作者能否写一个添加了白名单的注解的实现，给我们学习下呀

**Comment by Leifzhang** [comment]
已经开始开发了，最近比较忙，等开发完合并好了 告诉你

**Comment by Leifzhang** [comment]
好了  这个功能已经开发好了 顺便和lambda的问题也一起修复了  重新拉下master吧
