### ISSUE TITLE
请教一个asm 问题

### ISSUE THREAD

**Issue by haizhiyun** [Leifzhang/AndroidAutoTrack#36]
实现类似aspectJ @Around的功能，有什么思路吗？不想去看AspectJ 那么多代码 [拱手]

**Comment by Leifzhang** [comment]
这个在asm上只会更复杂 获取到method  之后在头尾都插入代码才行的

**Comment by haizhiyun** [comment]
> 这个在asm上只会更复杂 获取到method 之后在头尾都插入代码才行的

在方法头尾插入都还简单，但是要在方法中的某个指令的前后插入就比较难，有尝试过使用methodnode 在某个方法调用指令的前面加一条插入一个新的局部变量的指令吗

**Comment by Leifzhang** [comment]
你可以试试lancet的类替换机制  methodNode 插入的确可行 我个人看法

**Comment by haizhiyun** [comment]
> lancet

这个库，跑了下它说明文档上的例子都没效果，log.i 参数替换那个，感觉有点问题，methodNode 按理说在处理非方法头尾这种类型的插入，包括插入一个局部变量，都应该是tree api 擅长的操作，只是不知道为啥，我尝试了语句没报错，但结果也没成功 。。

**Comment by Leifzhang** [comment]
其实我个人觉得哦 你可以考虑下先定位到你所需要的AbstractInsnNode 之后在调用insert方法应该就可以了

**Comment by haizhiyun** [comment]
> 其实我个人觉得哦 你可以考虑下先定位到你所需要的AbstractInsnNode 之后在调用insert方法应该就可以了

是这么做的 但是没生效  目前只能用LocalVariablesSorter 这个类来搞了，这个类插入局部变量没问题，就是要自己去处理比较多的指令

**Comment by Leifzhang** [comment]
只能一点点试了 大佬  这个是比较难搞的  我之前插入也有出现过没有成功的状况 最后一点点试的

**Comment by haizhiyun** [comment]
感谢大佬回复  还在摸索学习中，以后有什么进展  再交流交流
