### ISSUE TITLE
重名名输出文件,因为可能同名,会覆盖

### ISSUE THREAD

**Issue by siyehua** [Leifzhang/AndroidAutoTrack#50]
在 baseTransform  类中看到这段代码： 

```
/* 重名名输出文件,因为可能同名,会覆盖*/
                    val hexName = DigestUtils.md5Hex(jarInput.file.absolutePath).substring(0, 8)
                    if (destName.endsWith(".jar")) {
                        destName = destName.substring(0, destName.length - 4)
                    }
                    /*获得输出文件*/
                    val dest = outputProvider!!.getContentLocation(
                            destName + "_" + hexName,
                            jarInput.contentTypes, jarInput.scopes, Format.JAR
                    )
```

我在项目中也碰到到 jar 名字重复的问题，主要是 classes.jar  可能是重复的

```
///直接使用 jar 的全路径作为名字可以吗？
                    val dest = outputProvider!!.getContentLocation(
                            jarInput.file.absolutePath,
                            jarInput.contentTypes, jarInput.scopes, Format.JAR
                    )
```
用这种方式可以吗？ 好像不一定要获取文件的 md5,路径是唯一的就能确定了

**Comment by Leifzhang** [comment]
这个只是短名字而已 并不能解决jar冲突问题

**Comment by Leifzhang** [comment]
如果是jar冲突的话 dex 合并的那个task肯定会挂的  解决方案完全不一样

**Comment by siyehua** [comment]
> 如果是jar冲突的话 dex 合并的那个task肯定会挂的 解决方案完全不一样

 jarInput.file.absolutePath 这个是唯一的呀，那个 File 的名字一样，path 也是不一样的。

我就是遇到了这个问题，有时候 dex 合并的时候会提示说类冲突（其实就是 jar 包重复了），但是我看了一下 path 都是一样的，不太明白为啥你的这种md5的可以，我用 path 的就不行

**Comment by Leifzhang** [comment]
有兴趣可以看下 __content__.json 这个文件，是对于数据的一个映射，我个人看法，name都是基于 modulename+version 所以jar冲突 应该冲突还是会冲突的

**Comment by siyehua** [comment]
老铁我看了这个文件，但是不知道要怎么弄，加你微信细聊，你微信多少



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月26日(周二) 中午12:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Leifzhang/AndroidAutoTrack] 重名名输出文件,因为可能同名,会覆盖 (Issue #50)




 
有兴趣可以看下 content.json 这个文件，是对于数据的一个映射，我个人看法，name都是基于 modulename+version 所以jar冲突 应该冲突还是会冲突的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
