### ISSUE TITLE
请教一个关于Asm捕捉全埋点时机的问题

### ISSUE THREAD

**Issue by WanDa1993** [Leifzhang/AndroidAutoTrack#51]
我最近在看Android全埋点那本书，我按照书上的方式，实现了最近的按钮事件捕捉。

然后在我深入测试的过程中，我发现按钮的Click事件在Kotlin中是存在两种表达：

```
      //第一种
      toolbar.setOnClickListener(object : View.OnClickListener {
            override fun onClick(v: View?) {
                Log.d("toolbar", "test")
                Log.d("toolbar", "test")
                Log.d("toolbar", "test")
                Log.d("toolbar", "test")
            }

        })
       //第二种
        toolbar.setOnClickListener {
            Log.d("toolbar", "test")
            Log.d("toolbar", "test")
            Log.d("toolbar", "test")
            Log.d("toolbar", "test")
        }
```
第一种情况下 我只需要匹配View$OnClickListener 匿名内部类以及onClick以及方法签名就可以

但是第二种我发现编译出来内容就不是内部类了，直接使用Kotlin的Function1来替代了，所以之前的捕捉逻辑就失效了。

最近一直在看你的插件和神策插件代码，但是由于刚开始接触还是看不明白。所以想请教下作者在插件中是如何实现这块内容的

**Comment by Leifzhang** [comment]
lambda 需要特殊处理的  已经不是匿名内部类了 现在由于脱糖在后 所以这块可以看下项目内的处理方式  
https://github.com/Leifzhang/AndroidAutoTrack/blob/master/Plugin/BasePlugin/src/main/java/com/kronos/plugin/base/asm/LambdaNodeHelper.kt
之前写过文章分析这部分内容 https://juejin.cn/post/6918733287015841800

**Comment by WanDa1993** [comment]
谢谢作者，我去了解下。
