### ISSUE TITLE
前后插件范围不同，导致 dependOn() 排序报错

### ISSUE THREAD

**Issue by JohnsonJLi** [Leifzhang/AndroidAutoTrack#55]
Unexpected scopes found in folder '*****/app/build/intermediates/transforms/DoubleTapTransform/debug'. Required: EXTERNAL_LIBRARIES. Found: EXTERNAL_LIBRARIES, PROJECT, SUB_PROJECTS

DoubleTapTransform  范围： Scope.PROJECT, Scope.SUB_PROJECTS, Scope.EXTERNAL_LIBRARIES
TimeLogTransform     范围： Scope.PROJECT, Scope.SUB_PROJECTS

想让 DoubleTapTransform（范围大）执行在 TimeLogTransform（范围小）之前

**Comment by Leifzhang** [comment]
这个是这样的  没啥特别好的办法  硬要做 可以考虑下用booster

**Comment by JohnsonJLi** [comment]
有没有那种方式 让范围一样， 过滤掉三方呢（除了包名匹配之外）？
