### ISSUE TITLE
大佬 请教一个 ASM 问题

### ISSUE THREAD

**Issue by JohnsonJLi** [Leifzhang/AndroidAutoTrack#56]
看了该项目之后启发很大自己学习扩展了一下，用 ASM 做了一些其他的尝试。

现在用ASM做一个简单的 路由框架 遇到了一些问题：

想要根据当前的 `ClassReader` 、`ClassNode` 判断当前 `Class` 是 `Activity`、`Fragment`、或者是其他类 
（java 中的 `instanceof Activity `， `instanceof Fragment` 操作），但是一直没有找到解决办法。

`ClassReader.superName` `ClassNode.superName` 只有当前父类 多级的情况无法满足。

求大佬指点！！！

**Comment by Leifzhang** [comment]
有几个不同的方式哦
 第一个放在apt的时候通过语法树来判断当前类型是什么，然后asm只负责收集路由表。
第二个可以考虑下用classloader 去把当前android 的源代码和所有的jar还有class 进行挂载，之后通过classloader来获取语法树。
第三个可以进行二次扫描，第一遍只负责进行对应的信息收集工作，最后第二遍的时候再进行字节码操作

**Comment by JohnsonJLi** [comment]
现在 只跳 Activity 的话 已经是满足了，  后续再加上apt吧；

**Comment by JohnsonJLi** [comment]
谢谢大佬
