### ISSUE TITLE
clone 下来 sync 后插件 中AppExtension引用不到 

### ISSUE THREAD

**Issue by caixingcun** [Leifzhang/AndroidAutoTrack#57]
![微信截图_20220606111224](https://user-images.githubusercontent.com/19374790/172088351-221bfc35-5b3a-46a4-bb66-c52558bf3894.png)

![微信截图_1](https://user-images.githubusercontent.com/19374790/172088387-f29ebe77-c099-4458-9767-43bab08c678e.png)

**Comment by Leifzhang** [comment]
同步的时候有什么异常提示吗 
看下as下面的有没有对应的agp的依赖
<img width="474" alt="image" src="https://user-images.githubusercontent.com/5960467/172091420-1a175e58-2026-421d-8d8f-e11c77a38c63.png">

**Comment by caixingcun** [comment]
没异常。。。。
谢谢  究极逮虾户 哥你的积极响应，我以为要等几天才能收到回复呢
下面的agp 都有 但就是AppExtension 引用不到 （想着应该是 gradle 的资源 问题）
我在每一个 plugin  项目下 又主动加了  gradle 然后就好了 
好像 BasePlugin 的 api 没生效 
![github](https://user-images.githubusercontent.com/19374790/172099818-acf2f6f6-000a-4b1f-81ac-e17aa3bca032.png)

**Comment by caixingcun** [comment]
发现问题了，AppExtension 在gradle 7.0.0 没有，在7.0.2 又给加回来了
